version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    environment:
      - NODE_ENV: test
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip bash
            pip install docker-compose
      - run:
          name: Build docker-compose images
          command: docker-compose build
      - run:
          name: Start service containers and run tests
          command: |
            docker-compose up -d
            docker-compose exec frontend yarn run test
